export const primary = "#4f52ff"
export const primaryLight = "#e3eafd"
export const primary2 = "#120878"
export const secondary = "#fe7062"
export const secondary2 = "#ff8e88"
export const backgroundColor = "#fff7f2"